### ISSUE TITLE
Screenshot URL broken in README

### ISSUE THREAD

**Issue by vikynandha** [stripe/gaps#14]
Looks like the screenshot in the "What it looks like" section is not available anymore.

![selection_639](https://cloud.githubusercontent.com/assets/1007270/7701654/f00cc878-fe46-11e4-8d54-f909fc140e9a.jpg)

**Comment by vikynandha** [comment]
Was it meant to be https://stripe.com/img/blog/posts/scaling-email-transparency/gaps.png ?

**Comment by kyleconroy** [comment]
This has been fixed! Thanks for the report
