### ISSUE TITLE
Missing authorization code after admin token has expired

### ISSUE THREAD

**Issue by sush** [stripe/gaps#4]
After a first sign in to Gaps with the domain's admin account and a successful fetch of the associated groups, the app crashes with the following stacktrace:

```
/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/signet-0.5.1/lib/signet/oauth_2/client.rb:906:in `generate_access_token_request': Missing authorization code. (ArgumentError)
	from /.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/signet-0.5.1/lib/signet/oauth_2/client.rb:930:in `fetch_access_token'
	from /.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/signet-0.5.1/lib/signet/oauth_2/client.rb:956:in `fetch_access_token!'
	from /dev/gaps/lib/gaps/db/user.rb:241:in `do_refresh'
	from /dev/gaps/lib/gaps/db/user.rb:101:in `client'
	from /dev/gaps/lib/gaps/requestor.rb:135:in `user_client'
	from /dev/gaps/lib/gaps/requestor.rb:143:in `get_client'
	from /dev/gaps/lib/gaps/requestor.rb:155:in `request'
	from /dev/gaps/lib/gaps/requestor.rb:193:in `block in request_all'
	from /.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/range/each.rb:7:in `each'
	from /.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/range/each.rb:7:in `each_with_time_with_zone'
	from /dev/gaps/lib/gaps/requestor.rb:189:in `request_all'
	from /dev/gaps/lib/gaps/requestor.rb:42:in `group_list'
	from /dev/gaps/lib/gaps/db/group.rb:177:in `refresh'
	from /dev/gaps/lib/gaps/db/group.rb:157:in `boot'
	from bin/gaps_server.rb:366:in `block in main'
	from /.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
	from /.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

I can't figure why but It seems that the refresh token isn't set in [`client.authorization`](https://github.com/stripe/gaps/blob/master/lib/gaps/db/user.rb#L241) when `fetch_access_token!` is called.

Any idea on the root cause?

Anyway, thanks for this great tool, very helpful in managing our mailing lists :)

**Comment by alvinlai** [comment]
Hi @sush, I suspect you've previously connected gaps, the refresh_token only seems to be returned on the first connect, where you'll see this:

![screen shot 2015-01-04 at 3 10 33 pm](https://cloud.githubusercontent.com/assets/24937/5607948/4839646c-9424-11e4-9b6b-537d87bb6631.png)

You could fix this by temporarily adding:

```ruby
authorization_options[:approval_prompt] = :force
```
after https://github.com/stripe/gaps/blob/master/bin/gaps_server.rb#L117 

@gdb would it be a good idea to set that `authorization_option` if the lister doesn't have a refresh_token set?

**Comment by alvinlai** [comment]
You can use my branch:

https://github.com/alvinlai/gaps/tree/force-refresh-token-first-time

to get the `refresh_token` persisted for the first time

specifically:

https://github.com/alvinlai/gaps/commit/5bfec15c44391e837cba1c390ad1378315720cb7

**Comment by gdb** [comment]
@alvinlai: Good find! Merging in your change.

**Comment by sush** [comment]
Thanks @alvinlai!

**Comment by DannyHernandez** [comment]
I'm getting a very similar error consistently. It started right after I changed the password on the admin account and restarted prod (running in docker). I don't get this error on my machine. My google app twitch-gaps doesn't have offline permission from my gmail account. I tried revoking access and now I get a different invalid credentials error. I think I need to delete the existing credentials. Where are they stored?

[2015-02-21 03:04:34.719315] [1] Refreshing expired token: user="<User[model_mLme704RR6] google_id=\"103975666791028339415\" email=\"danny@justin.tv\">"
== Sinatra has ended his set (crowd applauds)
/gaps/vendor/bundle/ruby/2.1.0/gems/signet-0.5.1/lib/signet/oauth_2/client.rb:906:in `generate_access_token_request': Missing authorization code. (raised from thread pool) (ArgumentError)
	from /gaps/vendor/bundle/ruby/2.1.0/gems/signet-0.5.1/lib/signet/oauth_2/client.rb:930:in `fetch_access_token'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/signet-0.5.1/lib/signet/oauth_2/client.rb:956:in `fetch_access_token!'
	from /gaps/lib/gaps/db/user.rb:241:in `do_refresh'
	from /gaps/lib/gaps/db/user.rb:101:in `client'
	from /gaps/lib/gaps/requestor.rb:131:in `lister_client'
	from /gaps/lib/gaps/requestor.rb:141:in `get_client'
	from /gaps/lib/gaps/requestor.rb:155:in `request'
	from /gaps/lib/gaps/requestor.rb:193:in `block in request_all'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/range/each.rb:7:in `each'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/range/each.rb:7:in `each_with_time_with_zone'
	from /gaps/lib/gaps/requestor.rb:189:in `request_all'
	from /gaps/lib/gaps/requestor.rb:68:in `membership_list'
	from /gaps/lib/gaps/requestor.rb:58:in `block in membership_list_for_group'
	from /gaps/lib/gaps/db/cache.rb:68:in `call'
	from /gaps/lib/gaps/db/cache.rb:68:in `block in cache_lookup'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:56:in `call'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:56:in `execute'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:384:in `block (2 levels) in spawn_thread'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:351:in `loop'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:351:in `block in spawn_thread'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
