### ISSUE TITLE
google-api-client Error

### ISSUE THREAD

**Issue by DannyHernandez** [stripe/gaps#7]
Hey,

I took this for a spin locally, and while running it directly I hit this google server error twice. I know it happened once while I was re-categorizing a list. Any ideas?

```
/Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/google-api-client-0.7.1/lib/google/api_client.rb:620:in `block in execute!': Backend Error (Google::APIClient::ServerError)
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/retriable-1.4.1/lib/retriable.rb:9:in `retriable'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/google-api-client-0.7.1/lib/google/api_client.rb:595:in `execute!'
	from /Users/danny/gaps/lib/gaps/requestor.rb:160:in `request'
	from /Users/danny/gaps/lib/gaps/requestor.rb:119:in `get_group_settings'
	from /Users/danny/gaps/lib/gaps/db/group.rb:95:in `update_config'
	from /Users/danny/gaps/lib/gaps/db/group.rb:187:in `block (2 levels) in refresh'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/thread-0.1.4/lib/thread/future.rb:27:in `call'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/thread-0.1.4/lib/thread/future.rb:27:in `block in initialize'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/thread-0.1.4/lib/thread/pool.rb:56:in `call'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/thread-0.1.4/lib/thread/pool.rb:56:in `execute'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/thread-0.1.4/lib/thread/pool.rb:384:in `block (2 levels) in spawn_thread'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/thread-0.1.4/lib/thread/pool.rb:351:in `loop'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/thread-0.1.4/lib/thread/pool.rb:351:in `block in spawn_thread'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by alvinlai** [comment]
Do you have `persist_config_to_group` in config.yaml set to true or false?

**Comment by DannyHernandez** [comment]
I don't have the field in my config.yaml. I have populate_group_settings as true. I've pasted my config.yaml below.

Dannys-MacBook-Air:gaps danny$ cat config.yaml 
default: &default
  cache:
    # How large of a threadpool to maintain for populating the cache
    # of what each list is subscribed to. (Note for implementation
    # reasons we'll actually be allocating 2x pool_size threads. Gaps
    # is network-bound, so having a larger number here than CPUs
    # should be fine.)
    pool_size: 10

    # Whether to serve possibly stale cache entries, in the name of a
    # faster pageload. Generally which list is subscribed to what
    # doesn't change that much, so allowing a stale load is fine.
    allow_stale: true

  healthcheck:
    # If $host_maintenance_dir/healthcheck.txt exists but is chmod'd
    # 000, consider this service down.
    host_maintenance_dir: /tmp/healthcheck/host
    # If $service_maintenance_dir/$name exists, consider this service
    # down.
    service_maintenance_dir: /tmp/healthcheck/service
    name: gaps

  oauth:
    # What scopes to ask for from each user upon login.
    common_scopes:
      - email
      - profile
    # What scopes to ask for from the lister upon initial login.
    lister_scopes:
      - https://www.googleapis.com/auth/admin.directory.user.readonly
      - https://www.googleapis.com/auth/admin.directory.group.readonly
      - https://apps-apis.google.com/a/feeds/emailsettings/2.0/
      - https://www.googleapis.com/auth/admin.directory.group.member
      - https://www.googleapis.com/auth/apps.groups.settings

  permissions:
    privacy_settings:
      # Whether to use the custom Gaps scheme (e.g. name starting with
      # acl-) to decide if a list is private.
      gaps_scheme: true
      # Whether to use the Google Groups Settings API to decide if a
      # list is private. (Can be composed with the Gaps scheme.)
      api_scheme: false

  # Whether to fetch the Google Groups settings upon group
  # refresh. Needed to make the api_scheme work. In the future will
  # probably power other features.
  populate_group_settings: true

development: *default
production: *default

**Comment by gdb** [comment]
Hm, I haven't see that before. Am I reading correctly that looks like an error being returned from Google's servers? Notice any patterns/can you consistently repo?

**Comment by DannyHernandez** [comment]
I haven't been able to consistently repo. 

The error always occured while a "Doing a full refresh of all groups" was in progress. Only 7/10 of the full refreshes have succeeded. Twitch also has more lists than people.

**Comment by alvinlai** [comment]
Not sure if related but Apple Mail had problems with GMail IMAP for a while this morning for me.

Nice to hear that Twitch is using lists extensively too! Would be nice if someone blogged more about that to encourage more companies to practice more internal email transparency.

**Comment by gdb** [comment]
Interesting. So there's already code to handle being rate limiting: https://github.com/stripe/gaps/blob/master/lib/gaps/requestor.rb#L186. Want to try expanding it to include `Backend error` too? All of the API calls Gaps makes are idempotent, so it shouldn't be dangerous.

**Comment by alvinlai** [comment]
Sounds good, so sort of like:

```ruby
rescue Google::APIClient::ServerError => e
  if e.message =~ /\ABackend Error/
  # sleep and retry here?
  else
    raise
  end
end
```

**Comment by gdb** [comment]
Yeah. On second thought, `create_filter` might not be idempotent, so that one should probably opt-out of retries on server error.

**Comment by DannyHernandez** [comment]
Thanks so much for all the quick help!  I pulled in master to test out the change and during the cache warming I hit a **NoMethodError**.

**requestor.rb:187:in `rescue in request': undefined method `<' for nil:NilClass (NoMethodError)**

**More Context**
[2015-01-09 13:15:01.381308] [62652] Refreshing cache: key="mygroupinfos:chrises@justin.tv"
[2015-01-09 13:15:01.381877] [62652] Finding all groups containing email (page: 0): uri="https://www.googleapis.com/admin/directory/v1/groups?domain=justin.tv&userKey=chrises%40justin.tv"
[2015-01-09 13:15:01.444893] [62652] Refreshing cache: key="mygroupinfos:chatbeta@justin.tv"
[2015-01-09 13:15:01.445565] [62652] Finding all groups containing email (page: 0): uri="https://www.googleapis.com/admin/directory/v1/groups?domain=justin.tv&userKey=chatbeta%40justin.tv"
== Sinatra has ended his set (crowd applauds)
/Users/danny/gaps/lib/gaps/requestor.rb:187:in `rescue in request': undefined method `<' for nil:NilClass (NoMethodError)
	from /Users/danny/gaps/lib/gaps/requestor.rb:177:in `request'
	from /Users/danny/gaps/lib/gaps/requestor.rb:223:in `block in request_all'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-4.1.8/lib/active_support/core_ext/range/each.rb:7:in `each'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-4.1.8/lib/active_support/core_ext/range/each.rb:7:in `each_with_time_with_zone'
	from /Users/danny/gaps/lib/gaps/requestor.rb:219:in `request_all'
	from /Users/danny/gaps/lib/gaps/requestor.rb:68:in `membership_list'
	from /Users/danny/gaps/lib/gaps/requestor.rb:58:in `block in membership_list_for_group'
	from /Users/danny/gaps/lib/gaps/db/cache.rb:68:in `call'
	from /Users/danny/gaps/lib/gaps/db/cache.rb:68:in `block in cache_lookup'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/thread-0.1.4/lib/thread/pool.rb:56:in `call'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/thread-0.1.4/lib/thread/pool.rb:56:in `execute'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/thread-0.1.4/lib/thread/pool.rb:384:in `block (2 levels) in spawn_thread'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/thread-0.1.4/lib/thread/pool.rb:351:in `loop'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/thread-0.1.4/lib/thread/pool.rb:351:in `block in spawn_thread'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
	from /Users/danny/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'

**Comment by gdb** [comment]
Whoops, sorry about that -- small bug with the patch. Try again with new master?

**Comment by DannyHernandez** [comment]
That did the trick. Thanks!

**Comment by DannyHernandez** [comment]
I've been hitting this error again while retrieving settings for groups :/.

[2015-02-28 19:38:25.992501] [1] Retrieving settings for group: uri="https://www.googleapis.com/groups/v1/groups/recruiting%40justin.tv"
== Sinatra has ended his set (crowd applauds)
/gaps/vendor/bundle/ruby/2.1.0/gems/google-api-client-0.7.1/lib/google/api_client.rb:620:in `block in execute!': Backend Error (Google::APIClient::ServerError)
	from /gaps/vendor/bundle/ruby/2.1.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/google-api-client-0.7.1/lib/google/api_client.rb:595:in `execute!'
	from /gaps/lib/gaps/requestor.rb:160:in `request'
	from /gaps/lib/gaps/requestor.rb:119:in `get_group_settings'
	from /gaps/lib/gaps/db/group.rb:95:in `update_config'
	from /gaps/lib/gaps/db/group.rb:187:in `block (2 levels) in refresh'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/future.rb:27:in `call'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/future.rb:27:in `block in initialize'

**Comment by gdb** [comment]
Nooooo. That's the same error as https://github.com/stripe/gaps/issues/9, right? Seems like that API is flaky on Google's side, and we should just catch and ignore the error. As a workaround, can you disable `populate_group_settings`?

**Comment by DannyHernandez** [comment]
It's the same error as #9. I'm still hitting it after disabling populate_group_settings.

      # Whether to use the Google Groups Settings API to decide if a
      # list is private. (Can be composed with the Gaps scheme.)
      api_scheme: false

  # Whether to fetch the Google Groups settings upon group
  # refresh. Needed to make the api_scheme work. In the future will
  # probably power other features.
  populate_group_settings: false

  persist_config_to_group: false

[2015-03-02 07:43:07.370725] [1] Retrieving settings for group: uri="https://www.googleapis.com/groups/v1/groups/domainmaster%40justin.tv"
[2015-03-02 07:43:07.663978] [1] Retrieving settings for group: uri="https://www.googleapis.com/groups/v1/groups/dreamhack%40justin.tv"
== Sinatra has ended his set (crowd applauds)
/gaps/vendor/bundle/ruby/2.1.0/gems/google-api-client-0.7.1/lib/google/api_client.rb:620:in `block in execute!': Backend Error (Google::APIClient::ServerError)
	from /gaps/vendor/bundle/ruby/2.1.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/google-api-client-0.7.1/lib/google/api_client.rb:595:in `execute!'
	from /gaps/lib/gaps/requestor.rb:160:in `request'
	from /gaps/lib/gaps/requestor.rb:119:in `get_group_settings'
	from /gaps/lib/gaps/db/group.rb:95:in `update_config'
	from /gaps/lib/gaps/db/group.rb:187:in `block (2 levels) in refresh'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/future.rb:27:in `call'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/future.rb:27:in `block in initialize'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:56:in `call'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:56:in `execute'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:384:in `block (2 levels) in spawn_thread'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:351:in `loop'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:351:in `block in spawn_thread'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'

**Comment by gdb** [comment]
Hm, that code should not be reachable with `populate_group_settings` off — maybe you have a site.yaml that's overriding your config settings or something?

Anyway, let me see if I can make Gaps start swallowing these errors rather than terminating...
